import { DiseaseTopic, Methodology, ResearchModality, PaperData, PublicationType, StudyType } from "./types";

export const APP_NAME = "BioInsight.AI";
export const APP_VERSION = "1.2.1 Live";

// Initial Data: Verified High-Impact Papers from 2024 (Jan - Present)
export const INITIAL_PAPERS: PaperData[] = [
  {
    id: 'finearts-2024',
    title: 'Finerenone in Heart Failure with Mildly Reduced or Preserved Ejection Fraction',
    journalOrConference: 'The New England Journal of Medicine',
    date: '2024-09-01',
    authors: ['S.D. Solomon', 'J.J.V. McMurray', 'et al.'],
    topic: DiseaseTopic.CVD,
    publicationType: PublicationType.PeerReviewed,
    studyType: StudyType.ClinicalTrial,
    methodology: Methodology.Statistical,
    modality: ResearchModality.ClinicalData,
    abstractHighlight: 'Finerenone resulted in a significantly lower rate of the composite of total worsening heart failure events or death from cardiovascular causes.',
    drugAndTarget: 'Target: Mineralocorticoid Receptor, Drug: Finerenone',
    context: 'FINEARTS-HF Trial results; first non-steroidal MRA to show benefit in HFmrEF/HFpEF.',
    validationScore: 100,
    url: 'https://www.nejm.org/doi/full/10.1056/NEJMoa2407107',
    authorsVerified: true,
    affiliations: ['Brigham and Women’s Hospital', 'University of Glasgow'],
    funding: 'Bayer',
    keywords: ['Heart Failure', 'HFpEF', 'Finerenone', 'Phase 3']
  },
  {
    id: 'synergy-nash-2024',
    title: 'Tirzepatide for Metabolic Dysfunction-Associated Steatohepatitis with Liver Fibrosis',
    journalOrConference: 'The New England Journal of Medicine',
    date: '2024-06-08',
    authors: ['R. Loomba', 'A.J. Sanyal', 'M.L. Kowdley', 'et al.'],
    topic: DiseaseTopic.MASH,
    publicationType: PublicationType.PeerReviewed,
    studyType: StudyType.ClinicalTrial,
    methodology: Methodology.Statistical,
    modality: ResearchModality.ClinicalData,
    abstractHighlight: 'In this phase 2 trial, tirzepatide was more effective than placebo in resolution of MASH with no worsening of fibrosis.',
    drugAndTarget: 'Target: GLP-1/GIP, Drug: Tirzepatide',
    context: 'SYNERGY-NASH Phase 2 results demonstrating significant efficacy.',
    validationScore: 100,
    url: 'https://www.nejm.org/doi/full/10.1056/NEJMoa2401943',
    authorsVerified: true,
    affiliations: ['University of California, San Diego', 'Virginia Commonwealth University'],
    funding: 'Eli Lilly',
    keywords: ['MASH', 'Fibrosis', 'Tirzepatide', 'Phase 2', 'SYNERGY-NASH']
  },
  {
    id: 'survodutide-2024',
    title: 'Glucagon-GLP-1 Receptor Dual Agonist Survodutide for MASH with Fibrosis',
    journalOrConference: 'The New England Journal of Medicine',
    date: '2024-06-21',
    authors: ['A.J. Sanyal', 'P. Bedossa', 'et al.'],
    topic: DiseaseTopic.MASH,
    publicationType: PublicationType.PeerReviewed,
    studyType: StudyType.ClinicalTrial,
    methodology: Methodology.Statistical,
    modality: ResearchModality.ClinicalData,
    abstractHighlight: 'Survodutide showed superiority to placebo in improvement of MASH without worsening of fibrosis.',
    drugAndTarget: 'Target: GCGR/GLP-1, Drug: Survodutide',
    context: 'Phase 2 trial results for a dual agonist in MASH treatment.',
    validationScore: 100,
    url: 'https://www.nejm.org/doi/full/10.1056/NEJMoa2401755',
    authorsVerified: true,
    affiliations: ['Virginia Commonwealth University', 'Boehringer Ingelheim'],
    funding: 'Boehringer Ingelheim',
    keywords: ['MASH', 'Survodutide', 'Dual Agonist', 'Phase 2']
  },
  {
    id: 'tirzepatide-osa-2024',
    title: 'Tirzepatide for the Treatment of Obstructive Sleep Apnea and Obesity',
    journalOrConference: 'The New England Journal of Medicine',
    date: '2024-06-21',
    authors: ['A. Malhotra', 'R.R. Grunstein', 'et al.'],
    topic: DiseaseTopic.Obesity,
    publicationType: PublicationType.PeerReviewed,
    studyType: StudyType.ClinicalTrial,
    methodology: Methodology.Statistical,
    modality: ResearchModality.ClinicalData,
    abstractHighlight: 'Tirzepatide significantly reduced the apnea-hypopnea index in patients with moderate-to-severe OSA and obesity.',
    drugAndTarget: 'Target: GLP-1/GIP, Drug: Tirzepatide',
    context: 'SURMOUNT-OSA Phase 3 results showing benefits beyond weight loss.',
    validationScore: 100,
    url: 'https://www.nejm.org/doi/full/10.1056/NEJMoa2404881',
    authorsVerified: true,
    affiliations: ['University of California, San Diego', 'Royal Prince Alfred Hospital'],
    funding: 'Eli Lilly',
    keywords: ['Obesity', 'Sleep Apnea', 'Tirzepatide', 'SURMOUNT-OSA']
  },
  {
    id: 'flow-ckd-2024',
    title: 'Effects of Semaglutide on Chronic Kidney Disease Outcomes in Type 2 Diabetes',
    journalOrConference: 'The New England Journal of Medicine',
    date: '2024-05-24',
    authors: ['V. Perkovic', 'K.R. Tuttle', 'et al.'],
    topic: DiseaseTopic.CKD,
    publicationType: PublicationType.PeerReviewed,
    studyType: StudyType.ClinicalTrial,
    methodology: Methodology.Statistical,
    modality: ResearchModality.ClinicalData,
    abstractHighlight: 'Semaglutide reduced the risk of major kidney disease events by 24% in patients with type 2 diabetes and CKD.',
    drugAndTarget: 'Target: GLP-1, Drug: Semaglutide',
    context: 'FLOW Trial results supporting renal protection standards.',
    validationScore: 100,
    url: 'https://www.nejm.org/doi/full/10.1056/NEJMoa2403347',
    authorsVerified: true,
    affiliations: ['University of New South Wales', 'University of Washington'],
    funding: 'Novo Nordisk',
    keywords: ['CKD', 'Semaglutide', 'Type 2 Diabetes', 'FLOW Trial']
  },
  {
    id: 'alphafold3-2024',
    title: 'Accurate structure prediction of biomolecular interactions with AlphaFold 3',
    journalOrConference: 'Nature',
    date: '2024-05-08',
    authors: ['J. Abramson', 'J. Adler', 'J. Dunger', 'et al.'],
    topic: DiseaseTopic.CVD, // Relevant for drug discovery across topics
    publicationType: PublicationType.PeerReviewed,
    studyType: StudyType.Simulated,
    methodology: Methodology.AIML,
    modality: ResearchModality.Proteomics,
    abstractHighlight: 'AlphaFold 3 predicts the structure of complexes including proteins, nucleic acids, small molecules, ions and modified residues.',
    drugAndTarget: 'Target: Pan-molecular',
    context: 'Major AI breakthrough for structural biology and drug design.',
    validationScore: 100,
    url: 'https://www.nature.com/articles/s41586-024-07487-w',
    authorsVerified: true,
    affiliations: ['Google DeepMind', 'Isomorphic Labs'],
    funding: 'Google',
    keywords: ['AI', 'Protein Structure', 'AlphaFold', 'Deep Learning']
  },
  {
    id: 'step-hfpef-dm-2024',
    title: 'Semaglutide in Patients with Obesity-Related Heart Failure and Type 2 Diabetes',
    journalOrConference: 'The New England Journal of Medicine',
    date: '2024-04-06',
    authors: ['M.N. Kosiborod', 'S.J. Shah', 'et al.'],
    topic: DiseaseTopic.CVD,
    publicationType: PublicationType.PeerReviewed,
    studyType: StudyType.ClinicalTrial,
    methodology: Methodology.Statistical,
    modality: ResearchModality.ClinicalData,
    abstractHighlight: 'Semaglutide led to larger reductions in heart failure-related symptoms and physical limitations in patients with HFpEF and T2D.',
    drugAndTarget: 'Target: GLP-1, Drug: Semaglutide',
    context: 'STEP-HFpEF DM results expanding GLP-1 use cases in cardiology.',
    validationScore: 100,
    url: 'https://www.nejm.org/doi/full/10.1056/NEJMoa2313917',
    authorsVerified: true,
    affiliations: ['Saint Luke’s Mid America Heart Institute', 'Northwestern University'],
    funding: 'Novo Nordisk',
    keywords: ['Heart Failure', 'Obesity', 'Semaglutide', 'Type 2 Diabetes']
  },
  {
    id: 'resmetirom-2024',
    title: 'Resmetirom for Nonalcoholic Steatohepatitis with Liver Fibrosis',
    journalOrConference: 'The New England Journal of Medicine',
    date: '2024-02-08',
    authors: ['S.A. Harrison', 'P. Bedossa', 'et al.'],
    topic: DiseaseTopic.NASH,
    publicationType: PublicationType.PeerReviewed,
    studyType: StudyType.ClinicalTrial,
    methodology: Methodology.Statistical,
    modality: ResearchModality.Imaging,
    abstractHighlight: 'Resmetirom treatment resulted in MASH resolution and fibrosis improvement in the phase 3 MAESTRO-NASH trial.',
    drugAndTarget: 'Target: THR-beta, Drug: Resmetirom',
    context: 'Foundational study for the first FDA-approved therapy for MASH/NASH.',
    validationScore: 100,
    url: 'https://www.nejm.org/doi/full/10.1056/NEJMoa2309000',
    authorsVerified: true,
    affiliations: ['Radcliffe Department of Medicine', 'University of Paris'],
    funding: 'Madrigal Pharmaceuticals',
    keywords: ['NASH', 'Resmetirom', 'Fibrosis', 'Phase 3']
  },
  {
    id: 'zilebesiran-2024',
    title: 'Zilebesiran, an RNA Interference Therapeutic Agent for Hypertension',
    journalOrConference: 'JAMA',
    date: '2024-01-23',
    authors: ['G.L. Bakris', 'M. Saxena', 'et al.'],
    topic: DiseaseTopic.CVD,
    publicationType: PublicationType.PeerReviewed,
    studyType: StudyType.ClinicalTrial,
    methodology: Methodology.Statistical,
    modality: ResearchModality.Genetics,
    abstractHighlight: 'KARDIA-1 Phase 2 study showed dose-dependent reductions in systolic blood pressure with zilebesiran.',
    drugAndTarget: 'Target: Angiotensinogen, Drug: Zilebesiran',
    context: 'Novel biannual RNAi therapy for hypertension.',
    validationScore: 100,
    url: 'https://jamanetwork.com/journals/jama/fullarticle/2815377',
    authorsVerified: true,
    affiliations: ['University of Chicago Medicine', 'Alnylam Pharmaceuticals'],
    funding: 'Alnylam Pharmaceuticals',
    keywords: ['Hypertension', 'RNAi', 'Zilebesiran', 'KARDIA-1']
  }
];